version: "3"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  nexus:
         container_name : nexus
         image: sonatype/nexus3
         ports:
                 - 8081:8081
         volumes:
                 - /home/${myname}


            
  sonar:
         container_name: sonar
         image: sonarqube
         restart: unless-stopped
         ports:

                 - 9000:9000
                 - 9092:9092


  mysqldb:
         container_name: mysqldb
         image: mysql:8
         environment:
                 MYSQL_ROOT_PASSWORD: admin
         ports:
                 - 3306:3306
         volumes:
                 - /home/mysqldata:/var/lib/msql
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    expose:
      - 9090
  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER='admin'
      - GF_SECURITY_ADMIN_PASSWORD= 'admin'
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
